name: plant_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: ^3.25.4
  image_picker: ^0.6.1+4
  carousel_slider: ^3.0.0
  flutter_svg: ^0.18.0
  dio: ^3.0.7
  intl: ^0.16.0
  retrofit: ^1.3.4+1
  firebase_messaging: ^7.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  retrofit_generator: ^1.4.1+1
  build_runner: ^1.10.12
  json_serializable: ^3.5.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


